---
abstract: 'turn a tabular file into a web application'
author:
  - 'Laurent Dami <laurent.dami@justice.ge.ch>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Tabular-Web
provides:
  File::Tabular::Web:
    file: lib/File/Tabular/Web.pm
    version: 0.20
  File::Tabular::Web::Attachments:
    file: lib/File/Tabular/Web/Attachments.pm
    version: 0
  File::Tabular::Web::Attachments::Indexed:
    file: lib/File/Tabular/Web/Attachments/Indexed.pm
    version: 0
recommends:
  Search::Indexer: 0.75
requires:
  AppConfig: 0
  CGI: 0
  Carp: 0
  File::Basename: 0
  File::Path: 0
  File::Tabular: 0.71
  List::MoreUtils: 0
  List::Util: 0
  POSIX: 0
  Scalar::Util: 0
  Search::QueryParser: 0.92
  Template: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
